"""Tests for v2.4.1 Yahboom visible placeholder stage and ROS 2 scaffold."""

import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent.parent

V241_DOC = "docs/v2.4.1_yahboom_visible_stage_ros2_scaffold.md"
V241_SCRIPT = "scripts/gnm/create_yahboom_visible_placeholder_stage.py"
USDA_PATH = "assets/robots/yahboom_m3_pro/yahboom_m3pro_visible_placeholder.usda"

V241_FILES = [V241_DOC, V241_SCRIPT]

ATTRIBUTION_STRINGS = [
    "generated by",
    "Generated by",
    "co-authored-by",
    "Co-Authored-By",
    "Claude",
    "Anthropic",
    "GPT",
    "ChatGPT",
    "OpenAI",
    "AI assistant",
    "language model",
]

REQUIRED_PRIMS = [
    "base_link",
    "top_deck",
    "camera_link",
    "lidar_link",
    "wheel_1",
    "wheel_2",
    "wheel_3",
    "wheel_4",
    "Ground",
]

CANONICAL_TOPICS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
]

NOVA_CARTER_TOPICS = [
    "/front_stereo_camera/left/image_raw",
    "/chassis/odom",
    "/front_3d_lidar/lidar_points",
]

DOC_REQUIRED_TERMS = [
    "base_link",
    "camera_link",
    "lidar_link",
    "wheel_1",
    "wheel_2",
    "wheel_3",
    "wheel_4",
    "Ground",
    "photo-realistic",
    "not photo-realistic",
    "OmniGraph",
    "ROS2PublishImage",
    "ROS2PublishOdometry",
    "ROS2PublishTransformTree",
    "ROS2PublishLaserScan",
    "ROS2SubscribeTwist",
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
    "Pending",
    "v2.4",
    "parameter_events",
    "rosout",
    "message_count",
    "Gate A5",
    "validate_yahboom_episode.py",
    "verify_yahboom_live_topics.py",
]


# ── File existence ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", V241_FILES)
def test_v241_file_exists(rel_path):
    assert (ROOT / rel_path).exists(), f"v2.4.1 file missing: {rel_path}"


def test_v241_script_executable():
    path = ROOT / V241_SCRIPT
    assert path.exists()
    assert os.access(path, os.X_OK), f"Script not executable: {V241_SCRIPT}"


# ── Attribution audit ─────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", V241_FILES)
def test_no_external_attribution(rel_path):
    path = ROOT / rel_path
    if not path.exists():
        pytest.skip(f"File not found: {rel_path}")
    content = path.read_text()
    for phrase in ATTRIBUTION_STRINGS:
        assert phrase not in content, (
            f"External attribution found in {rel_path}: {phrase!r}"
        )


# ── Doc required terms ────────────────────────────────────────────────────────

@pytest.mark.parametrize("term", DOC_REQUIRED_TERMS)
def test_doc_contains_required_term(term):
    doc = ROOT / V241_DOC
    assert doc.exists()
    assert term in doc.read_text(), (
        f"v2.4.1 doc missing required term: {term!r}"
    )


# ── Claim boundary assertions ─────────────────────────────────────────────────

def test_doc_says_not_photo_realistic():
    doc = ROOT / V241_DOC
    content = doc.read_text().lower()
    assert "not photo-realistic" in content, (
        "Doc must explicitly state the stage is NOT photo-realistic"
    )


def test_doc_says_no_valid_rosbag_recorded():
    doc = ROOT / V241_DOC
    content = doc.read_text()
    assert "Pending" in content
    assert "rosbag" in content.lower() or "rosbag2" in content.lower()
    assert "message_count" in content, (
        "Doc must reference message_count check to show no valid bag yet"
    )


def test_doc_says_ros2_publisher_pending():
    doc = ROOT / V241_DOC
    content = doc.read_text()
    assert "Pending" in content
    assert "OmniGraph" in content, (
        "Doc must say OmniGraph publisher nodes are still pending"
    )


def test_doc_explains_why_previous_usd_was_empty():
    doc = ROOT / V241_DOC
    content = doc.read_text()
    assert "absolute" in content.lower() or "reference" in content.lower(), (
        "Doc must explain that the previous USD was an absolute-path reference"
    )


def test_doc_lists_all_five_scaffold_node_types():
    doc = ROOT / V241_DOC
    content = doc.read_text()
    assert "ROS2PublishImage" in content
    assert "ROS2PublishOdometry" in content
    assert "ROS2PublishTransformTree" in content
    assert "ROS2PublishLaserScan" in content
    assert "ROS2SubscribeTwist" in content


@pytest.mark.parametrize("topic", CANONICAL_TOPICS)
def test_doc_mentions_canonical_topic(topic):
    doc = ROOT / V241_DOC
    assert topic in (ROOT / V241_DOC).read_text(), (
        f"v2.4.1 doc must mention canonical topic: {topic}"
    )


@pytest.mark.parametrize("topic", NOVA_CARTER_TOPICS)
def test_doc_does_not_mention_nova_carter_topics(topic):
    doc = ROOT / V241_DOC
    if not doc.exists():
        pytest.skip("Doc not found")
    assert topic not in doc.read_text(), (
        f"Nova Carter topic must not appear in v2.4.1 doc: {topic}"
    )


# ── Script content ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("prim", REQUIRED_PRIMS)
def test_script_defines_prim(prim):
    script = ROOT / V241_SCRIPT
    assert prim in script.read_text(), (
        f"Stage generator must define prim: {prim!r}"
    )


@pytest.mark.parametrize("topic", CANONICAL_TOPICS)
def test_script_references_canonical_topic(topic):
    script = ROOT / V241_SCRIPT
    assert topic in script.read_text(), (
        f"Stage generator must reference canonical topic in scaffold comments: {topic}"
    )


def test_script_says_not_photo_realistic():
    script = ROOT / V241_SCRIPT
    content = script.read_text().lower()
    assert "not photo-realistic" in content or "photo-realistic" in content, (
        "Stage generator must mention photo-realistic in claim boundary"
    )


def test_script_has_dry_run_flag():
    script = ROOT / V241_SCRIPT
    assert "--dry-run" in script.read_text()


def test_script_has_ros2_scaffold_comments():
    script = ROOT / V241_SCRIPT
    content = script.read_text()
    assert "ROS2PublishImage" in content
    assert "ROS2SubscribeTwist" in content


# ── Dry-run execution ─────────────────────────────────────────────────────────

def test_script_dry_run_exits_zero():
    result = subprocess.run(
        [sys.executable, str(ROOT / V241_SCRIPT), "--dry-run"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0, (
        f"create_yahboom_visible_placeholder_stage.py --dry-run failed:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert "[DRY-RUN]" in result.stdout
    assert "[OK]" in result.stdout


def test_script_dry_run_prints_usda_content():
    result = subprocess.run(
        [sys.executable, str(ROOT / V241_SCRIPT), "--dry-run"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    out = result.stdout
    assert "#usda 1.0" in out
    assert "base_link" in out
    assert "camera_link" in out
    assert "lidar_link" in out
    assert "wheel_1" in out
    assert "Ground" in out


def test_script_exits_zero():
    result = subprocess.run(
        [sys.executable, str(ROOT / V241_SCRIPT)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0, (
        f"create_yahboom_visible_placeholder_stage.py failed:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert "[OK]" in result.stdout


# ── USDA file content ─────────────────────────────────────────────────────────

def test_usda_file_exists_or_is_generated():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        # Generate it
        result = subprocess.run(
            [sys.executable, str(ROOT / V241_SCRIPT)],
            capture_output=True,
            text=True,
            cwd=str(ROOT),
        )
        assert result.returncode == 0, "Generator must exit 0"
    assert usda.exists(), f"USDA file must exist: {USDA_PATH}"


@pytest.mark.parametrize("prim", REQUIRED_PRIMS)
def test_usda_contains_prim(prim):
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated; run create_yahboom_visible_placeholder_stage.py")
    assert f'"{prim}"' in usda.read_text(), (
        f"USDA must contain prim definition: {prim!r}"
    )


def test_usda_has_correct_up_axis():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    assert 'upAxis = "Z"' in usda.read_text(), (
        "USDA must declare upAxis = Z (standard for robotics)"
    )


def test_usda_has_metres_per_unit():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    assert "metersPerUnit = 1" in usda.read_text(), (
        "USDA must use metersPerUnit = 1 (SI units)"
    )


def test_usda_has_scaffold_comments():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    content = usda.read_text()
    assert "ROS2Publish" in content, (
        "USDA scaffold comments must mention ROS2 publisher nodes"
    )
    assert "/camera/image_raw" in content
    assert "/odom" in content
    assert "Pending" in content


@pytest.mark.parametrize("topic", NOVA_CARTER_TOPICS)
def test_usda_does_not_reference_nova_carter(topic):
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    assert topic not in usda.read_text(), (
        f"USDA must not reference Nova Carter topic: {topic}"
    )


def test_usda_has_no_absolute_paths():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    content = usda.read_text()
    assert "/home/" not in content, (
        "USDA must not contain absolute filesystem paths — previous reference bug"
    )
    assert "FleetSafe-VisualNav-Benchmark" not in content, (
        "USDA must not reference the external FleetSafe benchmark repo path"
    )


# ── README ────────────────────────────────────────────────────────────────────

def test_readme_mentions_v241():
    readme = ROOT / "README.md"
    assert readme.exists()
    content = readme.read_text()
    assert "v2.4.1" in content, "README must mention v2.4.1"
