"""Tests for v2.2 Yahboom M3 Pro sim-to-real topic bridge prerequisites."""

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent.parent

V22_FILES = [
    "docs/v2.2_yahboom_m3pro_sim_to_real_plan.md",
    "scripts/gnm/discover_yahboom_assets.py",
    "scripts/gnm/check_yahboom_topic_contract.py",
]

EXECUTABLE_SCRIPTS = [
    "scripts/gnm/discover_yahboom_assets.py",
    "scripts/gnm/check_yahboom_topic_contract.py",
]

ATTRIBUTION_STRINGS = [
    "generated by",
    "Generated by",
    "co-authored-by",
    "Co-Authored-By",
    "Claude",
    "Anthropic",
    "GPT",
    "ChatGPT",
    "OpenAI",
    "AI assistant",
    "language model",
]

PLAN_REQUIRED_TERMS = [
    "URDF",
    "Unified Robot Description Format",
    "USD",
    "Universal Scene Description",
    "ROS 2",
    "Robot Operating System 2",
    "rosbag2",
    "TF",
    "cmd_vel",
    "mecanum",
    "sim-to-real",
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
    "Nova Carter",
    "smoke test",
    "Yahboom",
    "fl_wheel_joint",
    "/camera/color/image_raw",
]

CANONICAL_TOPICS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
]

NOVA_CARTER_TOPICS = [
    "/front_stereo_camera/left/image_raw",
    "/chassis/odom",
    "/front_3d_lidar/lidar_points",
]


@pytest.mark.parametrize("rel_path", V22_FILES)
def test_v22_file_exists(rel_path):
    path = ROOT / rel_path
    assert path.exists(), f"v2.2 file missing: {rel_path}"


@pytest.mark.parametrize("rel_path", EXECUTABLE_SCRIPTS)
def test_script_is_executable(rel_path):
    path = ROOT / rel_path
    assert path.exists(), f"Script missing: {rel_path}"
    assert os.access(path, os.X_OK), f"Script not executable: {rel_path}"


@pytest.mark.parametrize("term", PLAN_REQUIRED_TERMS)
def test_plan_contains_required_term(term):
    plan = ROOT / "docs" / "v2.2_yahboom_m3pro_sim_to_real_plan.md"
    assert plan.exists(), "v2.2 plan document missing"
    content = plan.read_text()
    assert term in content, f"Plan does not mention required term: {term!r}"


@pytest.mark.parametrize("rel_path", V22_FILES)
def test_no_external_attribution_in_v22_files(rel_path):
    path = ROOT / rel_path
    if not path.exists():
        pytest.skip(f"File not found: {rel_path}")
    content = path.read_text()
    for phrase in ATTRIBUTION_STRINGS:
        assert phrase not in content, (
            f"External attribution found in {rel_path}: {phrase!r}"
        )


@pytest.mark.parametrize("topic", CANONICAL_TOPICS)
def test_contract_script_references_canonical_topic(topic):
    script = ROOT / "scripts" / "gnm" / "check_yahboom_topic_contract.py"
    assert script.exists()
    assert topic in script.read_text(), (
        f"check_yahboom_topic_contract.py does not reference: {topic}"
    )


@pytest.mark.parametrize("topic", NOVA_CARTER_TOPICS)
def test_contract_script_references_nova_carter_topic(topic):
    script = ROOT / "scripts" / "gnm" / "check_yahboom_topic_contract.py"
    assert script.exists()
    assert topic in script.read_text(), (
        f"check_yahboom_topic_contract.py does not list Nova Carter topic: {topic}"
    )


def test_contract_script_references_camera_alias():
    script = ROOT / "scripts" / "gnm" / "check_yahboom_topic_contract.py"
    assert script.exists()
    content = script.read_text()
    assert "/camera/color/image_raw" in content, (
        "Topic contract must document the Yahboom hardware camera alias"
    )


def test_discover_yahboom_assets_exits_zero():
    script = ROOT / "scripts" / "gnm" / "discover_yahboom_assets.py"
    assert script.exists()
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0, (
        f"discover_yahboom_assets.py failed:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert "[OK]" in result.stdout, (
        f"Expected [OK] in output: {result.stdout}"
    )


def test_discover_yahboom_assets_writes_inventory(tmp_path):
    import tempfile, shutil, os as _os

    script = ROOT / "scripts" / "gnm" / "discover_yahboom_assets.py"
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0

    json_path = ROOT / "results" / "gnm_fleetsafe_v2_2" / "yahboom_asset_inventory.json"
    md_path = ROOT / "results" / "gnm_fleetsafe_v2_2" / "yahboom_asset_inventory.md"
    assert json_path.exists(), "yahboom_asset_inventory.json not written"
    assert md_path.exists(), "yahboom_asset_inventory.md not written"


def test_inventory_json_structure():
    json_path = ROOT / "results" / "gnm_fleetsafe_v2_2" / "yahboom_asset_inventory.json"
    if not json_path.exists():
        pytest.skip("Run discover_yahboom_assets.py first")
    data = json.loads(json_path.read_text())
    assert data["robot"] == "Yahboom ROSMASTER M3 Pro"
    assert "summary" in data
    assert "files" in data
    assert data["summary"]["has_urdf"] is True, "URDF must be present"


def test_inventory_json_finds_urdf():
    json_path = ROOT / "results" / "gnm_fleetsafe_v2_2" / "yahboom_asset_inventory.json"
    if not json_path.exists():
        pytest.skip("Run discover_yahboom_assets.py first")
    data = json.loads(json_path.read_text())
    assert len(data["files"]["urdf"]) > 0, "At least one Yahboom URDF must be found"


def test_inventory_json_finds_usd():
    json_path = ROOT / "results" / "gnm_fleetsafe_v2_2" / "yahboom_asset_inventory.json"
    if not json_path.exists():
        pytest.skip("Run discover_yahboom_assets.py first")
    data = json.loads(json_path.read_text())
    assert len(data["files"]["usd"]) > 0, "At least one Yahboom USD/USDA file must be found"


def test_check_yahboom_topic_contract_exits_zero():
    script = ROOT / "scripts" / "gnm" / "check_yahboom_topic_contract.py"
    assert script.exists()
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"check_yahboom_topic_contract.py must exit 0 without live robot:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )


def test_check_yahboom_topic_contract_strict_exits_nonzero_without_ros2():
    import shutil
    script = ROOT / "scripts" / "gnm" / "check_yahboom_topic_contract.py"
    assert script.exists()
    if shutil.which("ros2") is not None:
        pytest.skip("ROS 2 installed; strict-without-Yahboom check not applicable here")
    result = subprocess.run(
        [sys.executable, str(script), "--strict"],
        capture_output=True,
        text=True,
    )
    assert result.returncode != 0, (
        "check_yahboom_topic_contract.py --strict must exit non-zero without ROS 2"
    )


def test_plan_documents_scope_boundary():
    plan = ROOT / "docs" / "v2.2_yahboom_m3pro_sim_to_real_plan.md"
    content = plan.read_text()
    assert "v2.3" in content, (
        "Plan must reference v2.3 as the next milestone (rosbag episode)"
    )
    assert "Pending" in content, (
        "Plan must mark items still pending (e.g. live topic verification)"
    )


def test_plan_documents_mecanum_kinematics():
    plan = ROOT / "docs" / "v2.2_yahboom_m3pro_sim_to_real_plan.md"
    content = plan.read_text()
    assert "fl_wheel_joint" in content
    assert "fr_wheel_joint" in content
    assert "rl_wheel_joint" in content
    assert "rr_wheel_joint" in content


def test_readme_mentions_v22():
    readme = ROOT / "README.md"
    assert readme.exists()
    content = readme.read_text()
    assert "v2.2" in content, "README must mention v2.2"


def test_existing_yahboom_urdf_present():
    urdf = ROOT / "assets" / "robots" / "yahboom_m3_pro" / "yahboom_m3pro.urdf"
    assert urdf.exists(), (
        f"Canonical Yahboom URDF missing: {urdf.relative_to(ROOT)}"
    )


def test_existing_yahboom_usd_reference_present():
    usda = ROOT / "assets" / "robots" / "yahboom_m3_pro" / "yahboom_m3pro_reference.usda"
    assert usda.exists(), (
        f"Yahboom USD reference missing: {usda.relative_to(ROOT)}"
    )


def test_existing_yahboom_config_present():
    cfg = ROOT / "configs" / "robots" / "yahboom_m3_pro.yaml"
    assert cfg.exists(), (
        f"Yahboom robot config missing: {cfg.relative_to(ROOT)}"
    )


def test_existing_yahboom_xacro_present():
    xacro = (
        ROOT
        / "ros2_ws"
        / "src"
        / "fleet_safe_description"
        / "urdf"
        / "yahboom_m3pro.urdf.xacro"
    )
    assert xacro.exists(), (
        f"Yahboom Xacro missing: {xacro.relative_to(ROOT)}"
    )
