"""Tests for Yahboom upstream integration: clone script, inspector, topic mapping."""

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent.parent

INTEGRATION_DOCS = [
    "docs/yahboom_upstream_integration.md",
    "docs/yahboom_to_fleetsafe_topic_mapping.md",
]

INTEGRATION_SCRIPTS = [
    "scripts/setup/clone_yahboom_rosmaster_m3pro.sh",
    "scripts/gnm/inspect_yahboom_upstream.py",
]

ATTRIBUTION_STRINGS = [
    "generated by",
    "Generated by",
    "co-authored-by",
    "Co-Authored-By",
    "Claude",
    "Anthropic",
    "GPT",
    "ChatGPT",
    "OpenAI",
    "AI assistant",
    "language model",
]

CANONICAL_TOPICS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
]

UPSTREAM_URL = "https://github.com/YahboomTechnology/ROSMASTER-M3PRO"

INTEGRATION_DOC_REQUIRED_TERMS = [
    "YahboomTechnology/ROSMASTER-M3PRO",
    "external/yahboom/ROSMASTER-M3PRO",
    "GNM",
    "FleetSafe",
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
    "OpenClaw",
    "SLAM",
    "Track B",
    "sim-to-real",
    "gitignore",
    "Pending",
    "clone_yahboom_rosmaster_m3pro.sh",
    "inspect_yahboom_upstream.py",
]

TOPIC_MAPPING_REQUIRED_TERMS = [
    "/camera/image_raw",
    "/camera/color/image_raw",
    "/odom",
    "/m3pro/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
    "/m3pro/cmd_vel",
    "mecanum",
    "remappings",
    "verify_yahboom_live_topics.py",
    "CBF",
    "Twist",
    "geometry_msgs",
    "lx",
    "ly",
]


# ── File existence ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", INTEGRATION_DOCS + INTEGRATION_SCRIPTS)
def test_file_exists(rel_path):
    assert (ROOT / rel_path).exists(), f"Integration file missing: {rel_path}"


@pytest.mark.parametrize("rel_path", INTEGRATION_SCRIPTS)
def test_script_executable(rel_path):
    path = ROOT / rel_path
    assert path.exists(), f"Script missing: {rel_path}"
    assert os.access(path, os.X_OK), f"Script not executable: {rel_path}"


# ── Attribution audit ─────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", INTEGRATION_DOCS + INTEGRATION_SCRIPTS)
def test_no_external_attribution(rel_path):
    path = ROOT / rel_path
    if not path.exists():
        pytest.skip(f"File not found: {rel_path}")
    content = path.read_text()
    for phrase in ATTRIBUTION_STRINGS:
        assert phrase not in content, (
            f"External attribution found in {rel_path}: {phrase!r}"
        )


# ── Integration doc required terms ───────────────────────────────────────────

@pytest.mark.parametrize("term", INTEGRATION_DOC_REQUIRED_TERMS)
def test_integration_doc_contains_term(term):
    doc = ROOT / "docs" / "yahboom_upstream_integration.md"
    assert doc.exists()
    assert term in doc.read_text(), (
        f"yahboom_upstream_integration.md missing required term: {term!r}"
    )


def test_integration_doc_states_gitignored():
    doc = ROOT / "docs" / "yahboom_upstream_integration.md"
    content = doc.read_text()
    assert "gitignore" in content or "gitignored" in content, (
        "Integration doc must state that external/ is gitignored"
    )


def test_integration_doc_has_two_layer_diagram():
    doc = ROOT / "docs" / "yahboom_upstream_integration.md"
    content = doc.read_text()
    assert "Yahboom official repo" in content or "Yahboom robot hardware" in content
    assert "GNM" in content
    assert "FleetSafe" in content


def test_integration_doc_explains_openclaw_scope():
    doc = ROOT / "docs" / "yahboom_upstream_integration.md"
    content = doc.read_text()
    assert "OpenClaw" in content
    assert "optional" in content.lower()


def test_integration_doc_explains_slam():
    doc = ROOT / "docs" / "yahboom_upstream_integration.md"
    content = doc.read_text()
    assert "SLAM" in content
    assert "Simultaneous" in content


# ── Topic mapping doc required terms ─────────────────────────────────────────

@pytest.mark.parametrize("term", TOPIC_MAPPING_REQUIRED_TERMS)
def test_topic_mapping_doc_contains_term(term):
    doc = ROOT / "docs" / "yahboom_to_fleetsafe_topic_mapping.md"
    assert doc.exists()
    assert term in doc.read_text(), (
        f"yahboom_to_fleetsafe_topic_mapping.md missing required term: {term!r}"
    )


@pytest.mark.parametrize("topic", CANONICAL_TOPICS)
def test_topic_mapping_doc_contains_canonical_topic(topic):
    doc = ROOT / "docs" / "yahboom_to_fleetsafe_topic_mapping.md"
    assert topic in doc.read_text(), (
        f"Topic mapping doc must mention canonical topic: {topic}"
    )


def test_topic_mapping_doc_states_camera_alias():
    doc = ROOT / "docs" / "yahboom_to_fleetsafe_topic_mapping.md"
    content = doc.read_text()
    assert "/camera/color/image_raw" in content
    assert "/camera/image_raw" in content


def test_topic_mapping_doc_states_odom_remap():
    doc = ROOT / "docs" / "yahboom_to_fleetsafe_topic_mapping.md"
    content = doc.read_text()
    assert "/m3pro/odom" in content
    assert "/odom" in content


def test_topic_mapping_doc_states_cmdvel_remap():
    doc = ROOT / "docs" / "yahboom_to_fleetsafe_topic_mapping.md"
    content = doc.read_text()
    assert "/m3pro/cmd_vel" in content
    assert "/cmd_vel" in content


def test_topic_mapping_doc_has_launch_file_example():
    doc = ROOT / "docs" / "yahboom_to_fleetsafe_topic_mapping.md"
    content = doc.read_text()
    assert "remappings" in content
    assert "generate_launch_description" in content or "LaunchDescription" in content


# ── Clone script content ──────────────────────────────────────────────────────

def test_clone_script_references_upstream_url():
    script = ROOT / "scripts" / "setup" / "clone_yahboom_rosmaster_m3pro.sh"
    assert UPSTREAM_URL in script.read_text(), (
        "Clone script must reference the official Yahboom upstream URL"
    )


def test_clone_script_targets_external_dir():
    script = ROOT / "scripts" / "setup" / "clone_yahboom_rosmaster_m3pro.sh"
    content = script.read_text()
    assert "external/yahboom/ROSMASTER-M3PRO" in content


def test_clone_script_has_dry_run_flag():
    script = ROOT / "scripts" / "setup" / "clone_yahboom_rosmaster_m3pro.sh"
    assert "--dry-run" in script.read_text()


def test_clone_script_has_update_flag():
    script = ROOT / "scripts" / "setup" / "clone_yahboom_rosmaster_m3pro.sh"
    assert "--update" in script.read_text()


def test_clone_script_warns_about_gitignore():
    script = ROOT / "scripts" / "setup" / "clone_yahboom_rosmaster_m3pro.sh"
    content = script.read_text()
    assert "gitignore" in content or "not be committed" in content


# ── Inspector script content ──────────────────────────────────────────────────

def test_inspector_references_upstream_url():
    script = ROOT / "scripts" / "gnm" / "inspect_yahboom_upstream.py"
    assert UPSTREAM_URL in script.read_text()


def test_inspector_references_external_dir():
    script = ROOT / "scripts" / "gnm" / "inspect_yahboom_upstream.py"
    assert "external/yahboom/ROSMASTER-M3PRO" in script.read_text()


def test_inspector_searches_canonical_topics():
    script = ROOT / "scripts" / "gnm" / "inspect_yahboom_upstream.py"
    content = script.read_text()
    assert "cmd_vel" in content
    assert "odom" in content
    assert "scan" in content
    assert "camera" in content


def test_inspector_searches_for_urdf():
    script = ROOT / "scripts" / "gnm" / "inspect_yahboom_upstream.py"
    assert ".urdf" in script.read_text()


def test_inspector_searches_for_mecanum():
    script = ROOT / "scripts" / "gnm" / "inspect_yahboom_upstream.py"
    assert "mecanum" in script.read_text()


def test_inspector_searches_for_openclaw():
    script = ROOT / "scripts" / "gnm" / "inspect_yahboom_upstream.py"
    assert "openclaw" in script.read_text().lower()


def test_inspector_writes_json_output():
    script = ROOT / "scripts" / "gnm" / "inspect_yahboom_upstream.py"
    content = script.read_text()
    assert "yahboom_upstream_inventory.json" in content
    assert "results/yahboom_upstream" in content


# ── Dry-run script execution ──────────────────────────────────────────────────

def test_clone_script_dry_run_exits_zero():
    script = ROOT / "scripts" / "setup" / "clone_yahboom_rosmaster_m3pro.sh"
    result = subprocess.run(
        ["bash", str(script), "--dry-run"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0, (
        f"clone_yahboom_rosmaster_m3pro.sh --dry-run failed:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert "[DRY-RUN]" in result.stdout
    assert UPSTREAM_URL in result.stdout
    assert "[OK]" in result.stdout


def test_clone_script_dry_run_prints_git_clone():
    script = ROOT / "scripts" / "setup" / "clone_yahboom_rosmaster_m3pro.sh"
    result = subprocess.run(
        ["bash", str(script), "--dry-run"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert "git clone" in result.stdout
    assert UPSTREAM_URL in result.stdout


def test_inspector_exits_zero_without_upstream():
    script = ROOT / "scripts" / "gnm" / "inspect_yahboom_upstream.py"
    upstream_dir = ROOT / "external" / "yahboom" / "ROSMASTER-M3PRO"
    if upstream_dir.exists():
        pytest.skip("Upstream repo is cloned; not a no-clone test")
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0, (
        f"inspect_yahboom_upstream.py must exit 0 without upstream clone:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert "[OK]" in result.stdout
    assert "clone" in result.stdout.lower()


def test_inspector_writes_status_json_without_upstream():
    script = ROOT / "scripts" / "gnm" / "inspect_yahboom_upstream.py"
    upstream_dir = ROOT / "external" / "yahboom" / "ROSMASTER-M3PRO"
    if upstream_dir.exists():
        pytest.skip("Upstream repo is cloned; skip not-cloned JSON test")
    subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        cwd=str(ROOT),
    )
    json_path = ROOT / "results" / "yahboom_upstream" / "yahboom_upstream_inventory.json"
    assert json_path.exists(), "Inspector must write inventory JSON even without upstream"
    data = json.loads(json_path.read_text())
    assert data["status"] == "not_cloned"
    assert data["upstream_url"] == UPSTREAM_URL
    assert "clone_command" in data


# ── .gitignore check ──────────────────────────────────────────────────────────

def test_external_dir_is_gitignored():
    gitignore = ROOT / ".gitignore"
    if not gitignore.exists():
        pytest.skip(".gitignore not found")
    content = gitignore.read_text()
    assert "external/" in content or "external/yahboom" in content, (
        "external/ must be listed in .gitignore so the Yahboom clone is never committed"
    )


# ── README ────────────────────────────────────────────────────────────────────

def test_readme_mentions_yahboom_upstream():
    readme = ROOT / "README.md"
    assert readme.exists()
    content = readme.read_text()
    assert "Yahboom" in content, "README must mention Yahboom"
