"""Tests for v2.3 Yahboom M3 Pro Isaac import and canonical topic verification."""

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent.parent

V23_DOCS = [
    "docs/v2.3_yahboom_isaac_import_topic_verification.md",
    "docs/track_a_track_b_completion_gates.md",
]

V23_SCRIPTS = [
    "scripts/gnm/yahboom_isaac_import_plan.py",
    "scripts/gnm/verify_yahboom_live_topics.py",
]

ATTRIBUTION_STRINGS = [
    "generated by",
    "Generated by",
    "co-authored-by",
    "Co-Authored-By",
    "Claude",
    "Anthropic",
    "GPT",
    "ChatGPT",
    "OpenAI",
    "AI assistant",
    "language model",
]

# Every acronym that must be expanded in the v2.3 main doc.
REQUIRED_ACRONYM_EXPANSIONS = [
    ("ROS 2", "Robot Operating System 2"),
    ("URDF", "Unified Robot Description Format"),
    ("Xacro", "XML Macro"),
    ("USD", "Universal Scene Description"),
    ("TF", "Transform"),
    ("RGB", "Red Green Blue"),
    ("LiDAR", "Light Detection and Ranging"),
]

# Terms that must appear in the v2.3 doc.
V23_DOC_REQUIRED_TERMS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
    "smoke test",
    "Nova Carter",
    "Yahboom",
    "canonical",
    "strict",
    "rosbag2",
    "mecanum",
    "fl_wheel_joint",
    "/camera/color/image_raw",
    "v2.4",
]

# Terms that must appear in the Track A/B gates doc.
GATES_DOC_REQUIRED_TERMS = [
    "Track A",
    "Track B",
    "SR",
    "Success Rate",
    "OSR",
    "Oracle Success Rate",
    "NE",
    "Navigation Error",
    "CBF",
    "Control Barrier Function",
    "QP",
    "Quadratic Program",
    "Gate A1",
    "Gate A5",
    "Gate A6",
    "Gate B1",
    "Gate B2",
    "language",
    "held-out",
    "Pending",
    "Complete",
]

CANONICAL_TOPICS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
]


# ── File existence ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", V23_DOCS + V23_SCRIPTS)
def test_v23_file_exists(rel_path):
    assert (ROOT / rel_path).exists(), f"v2.3 file missing: {rel_path}"


@pytest.mark.parametrize("rel_path", V23_SCRIPTS)
def test_script_is_executable(rel_path):
    path = ROOT / rel_path
    assert path.exists(), f"Script missing: {rel_path}"
    assert os.access(path, os.X_OK), f"Script not executable: {rel_path}"


# ── Attribution audit ─────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", V23_DOCS + V23_SCRIPTS)
def test_no_external_attribution(rel_path):
    path = ROOT / rel_path
    if not path.exists():
        pytest.skip(f"File not found: {rel_path}")
    content = path.read_text()
    for phrase in ATTRIBUTION_STRINGS:
        assert phrase not in content, (
            f"External attribution found in {rel_path}: {phrase!r}"
        )


# ── Acronym expansion ─────────────────────────────────────────────────────────

@pytest.mark.parametrize("acronym,expansion", REQUIRED_ACRONYM_EXPANSIONS)
def test_v23_doc_expands_acronym(acronym, expansion):
    doc = ROOT / "docs" / "v2.3_yahboom_isaac_import_topic_verification.md"
    assert doc.exists()
    content = doc.read_text()
    assert acronym in content, f"Acronym {acronym!r} not mentioned"
    assert expansion in content, (
        f"Acronym {acronym!r} is not expanded to {expansion!r}"
    )


# ── Required terms ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("term", V23_DOC_REQUIRED_TERMS)
def test_v23_doc_contains_required_term(term):
    doc = ROOT / "docs" / "v2.3_yahboom_isaac_import_topic_verification.md"
    assert doc.exists()
    assert term in doc.read_text(), f"v2.3 doc missing required term: {term!r}"


@pytest.mark.parametrize("term", GATES_DOC_REQUIRED_TERMS)
def test_gates_doc_contains_required_term(term):
    doc = ROOT / "docs" / "track_a_track_b_completion_gates.md"
    assert doc.exists()
    assert term in doc.read_text(), (
        f"Track A/B gates doc missing required term: {term!r}"
    )


# ── Topic references in scripts ───────────────────────────────────────────────

@pytest.mark.parametrize("topic", CANONICAL_TOPICS)
def test_verify_script_references_canonical_topic(topic):
    script = ROOT / "scripts" / "gnm" / "verify_yahboom_live_topics.py"
    assert script.exists()
    assert topic in script.read_text(), (
        f"verify_yahboom_live_topics.py must reference: {topic}"
    )


def test_verify_script_references_camera_alias():
    script = ROOT / "scripts" / "gnm" / "verify_yahboom_live_topics.py"
    assert "/camera/color/image_raw" in script.read_text(), (
        "Verifier must document the Yahboom hardware camera alias"
    )


def test_verify_script_references_nova_carter():
    script = ROOT / "scripts" / "gnm" / "verify_yahboom_live_topics.py"
    content = script.read_text()
    assert "/front_stereo_camera/left/image_raw" in content, (
        "Verifier must list Nova Carter smoke-test topics to guard against"
    )


# ── Dry-run script execution ──────────────────────────────────────────────────

def test_import_plan_exits_zero():
    script = ROOT / "scripts" / "gnm" / "yahboom_isaac_import_plan.py"
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0, (
        f"yahboom_isaac_import_plan.py failed:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert "[OK]" in result.stdout


def test_import_plan_writes_outputs():
    script = ROOT / "scripts" / "gnm" / "yahboom_isaac_import_plan.py"
    subprocess.run([sys.executable, str(script)], capture_output=True, cwd=str(ROOT))

    json_path = ROOT / "results" / "gnm_fleetsafe_v2_3" / "yahboom_isaac_import_plan.json"
    md_path = ROOT / "results" / "gnm_fleetsafe_v2_3" / "yahboom_isaac_import_plan.md"
    assert json_path.exists(), "yahboom_isaac_import_plan.json not written"
    assert md_path.exists(), "yahboom_isaac_import_plan.md not written"


def test_import_plan_json_structure():
    json_path = ROOT / "results" / "gnm_fleetsafe_v2_3" / "yahboom_isaac_import_plan.json"
    if not json_path.exists():
        pytest.skip("Run yahboom_isaac_import_plan.py first")
    data = json.loads(json_path.read_text())
    assert data["robot"] == "Yahboom ROSMASTER M3 Pro"
    assert "import_steps" in data
    assert len(data["import_steps"]) == 11
    assert "assets" in data
    assert data["assets"]["canonical_urdf"]["exists"] is True


def test_import_plan_json_urdf_present():
    json_path = ROOT / "results" / "gnm_fleetsafe_v2_3" / "yahboom_isaac_import_plan.json"
    if not json_path.exists():
        pytest.skip("Run yahboom_isaac_import_plan.py first")
    data = json.loads(json_path.read_text())
    assert data["assets"]["canonical_urdf"]["exists"], "Canonical URDF must be present"


def test_import_plan_json_first_blocking_step():
    json_path = ROOT / "results" / "gnm_fleetsafe_v2_3" / "yahboom_isaac_import_plan.json"
    if not json_path.exists():
        pytest.skip("Run yahboom_isaac_import_plan.py first")
    data = json.loads(json_path.read_text())
    step = data["first_blocking_step"]
    assert isinstance(step, int)
    assert 1 <= step <= 11, f"first_blocking_step {step} out of expected range"


def test_verify_topics_exits_zero_without_live_robot():
    script = ROOT / "scripts" / "gnm" / "verify_yahboom_live_topics.py"
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"verify_yahboom_live_topics.py must exit 0 without Isaac Sim:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )


def test_verify_topics_strict_nonzero_without_ros2():
    import shutil
    script = ROOT / "scripts" / "gnm" / "verify_yahboom_live_topics.py"
    if shutil.which("ros2") is not None:
        pytest.skip("ROS 2 installed; strict-without-Yahboom not applicable here")
    result = subprocess.run(
        [sys.executable, str(script), "--strict"],
        capture_output=True,
        text=True,
    )
    assert result.returncode != 0, (
        "verify_yahboom_live_topics.py --strict must exit non-zero without ROS 2"
    )


# ── Claim boundary ────────────────────────────────────────────────────────────

def test_v23_doc_has_claim_boundary_table():
    doc = ROOT / "docs" / "v2.3_yahboom_isaac_import_topic_verification.md"
    content = doc.read_text()
    assert "Pending" in content, "Claim boundary must mark pending items"
    assert "v2.4" in content, "Claim boundary must name the next milestone"


def test_gates_doc_marks_completed_track_a_gates():
    doc = ROOT / "docs" / "track_a_track_b_completion_gates.md"
    content = doc.read_text()
    assert "Complete" in content, "Gates doc must mark some gates as complete"
    assert "A1" in content
    assert "A2" in content
    assert "A3" in content


def test_gates_doc_marks_track_b_pending():
    doc = ROOT / "docs" / "track_a_track_b_completion_gates.md"
    content = doc.read_text()
    assert "B1" in content
    assert "B6" in content


# ── Existing asset presence (pre-conditions for v2.3) ────────────────────────

def test_canonical_yahboom_urdf_present():
    urdf = ROOT / "assets" / "robots" / "yahboom_m3_pro" / "yahboom_m3pro.urdf"
    assert urdf.exists(), f"Canonical Yahboom URDF must exist: {urdf.relative_to(ROOT)}"


def test_canonical_yahboom_usd_present():
    usd = ROOT / "assets" / "robots" / "yahboom_m3_pro" / "yahboom_m3pro.usd"
    assert usd.exists(), f"Canonical Yahboom USD must exist: {usd.relative_to(ROOT)}"


def test_yahboom_reference_usda_present():
    usda = ROOT / "assets" / "robots" / "yahboom_m3_pro" / "yahboom_m3pro_reference.usda"
    assert usda.exists(), f"Yahboom reference USDA must exist: {usda.relative_to(ROOT)}"


def test_yahboom_import_doc_present():
    doc = ROOT / "docs" / "YAHBOOM_URDF_TO_USD_IMPORT.md"
    assert doc.exists(), "YAHBOOM_URDF_TO_USD_IMPORT.md must exist"


# ── README ────────────────────────────────────────────────────────────────────

def test_readme_mentions_v23():
    readme = ROOT / "README.md"
    assert readme.exists()
    content = readme.read_text()
    assert "v2.3" in content, "README must mention v2.3"
