"""Tests for v2.4.2 Yahboom ROS 2 OmniGraph publisher scaffold."""

import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent.parent

V242_DOC = "docs/v2.4.2_yahboom_omnigraph_publishers.md"
V242_OMNIGRAPH_SCRIPT = "scripts/gnm/add_yahboom_ros2_omnigraph.py"
V241_STAGE_SCRIPT = "scripts/gnm/create_yahboom_visible_placeholder_stage.py"
USDA_PATH = "assets/robots/yahboom_m3_pro/yahboom_m3pro_visible_placeholder.usda"

V242_FILES = [V242_DOC, V242_OMNIGRAPH_SCRIPT]

ATTRIBUTION_STRINGS = [
    "generated by",
    "Generated by",
    "co-authored-by",
    "Co-Authored-By",
    "Claude",
    "Anthropic",
    "GPT",
    "ChatGPT",
    "OpenAI",
    "AI assistant",
    "language model",
]

CANONICAL_TOPICS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
]

NOVA_CARTER_TOPICS = [
    "/front_stereo_camera/left/image_raw",
    "/chassis/odom",
    "/front_3d_lidar/lidar_points",
]

OMNIGRAPH_NODE_TYPES = [
    "omni.graph.action.OnPlaybackTick",
    "omni.isaac.ros2_bridge.ROS2Context",
    "omni.isaac.ros2_bridge.ROS2PublishImage",
    "omni.isaac.ros2_bridge.ROS2PublishOdometry",
    "omni.isaac.ros2_bridge.ROS2PublishTransformTree",
    "omni.isaac.ros2_bridge.ROS2PublishLaserScan",
    "omni.isaac.ros2_bridge.ROS2SubscribeTwist",
]

PRIM_PATHS = [
    "/World/YahboomM3Pro",
    "/World/YahboomM3Pro/base_link",
    "/World/YahboomM3Pro/camera_link/sensor",
    "/World/YahboomM3Pro/lidar_link",
    "/World/ROS2ActionGraph",
]

DOC_REQUIRED_TERMS = [
    "OmniGraph",
    "ROS2Context",
    "ROS2PublishImage",
    "ROS2PublishOdometry",
    "ROS2PublishTransformTree",
    "ROS2PublishLaserScan",
    "ROS2SubscribeTwist",
    "OnPlaybackTick",
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
    "verify_yahboom_live_topics.py",
    "--strict",
    "Gate A5",
    "add_yahboom_ros2_omnigraph.py",
    "camera_link/sensor",
    "base_link",
    "lidar_link",
    "Pending",
    "message_count",
    "v2.4.1",
    "v2.4.3",
    "parameter_events",
    "rosout",
    "not photo-realistic",
    "ROS2ActionGraph",
]


# ── File existence ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", V242_FILES)
def test_v242_file_exists(rel_path):
    assert (ROOT / rel_path).exists(), f"v2.4.2 file missing: {rel_path}"


def test_omnigraph_script_executable():
    path = ROOT / V242_OMNIGRAPH_SCRIPT
    assert path.exists()
    assert os.access(path, os.X_OK), f"Script not executable: {V242_OMNIGRAPH_SCRIPT}"


# ── Attribution audit ─────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", V242_FILES)
def test_no_external_attribution(rel_path):
    path = ROOT / rel_path
    if not path.exists():
        pytest.skip(f"File not found: {rel_path}")
    content = path.read_text()
    for phrase in ATTRIBUTION_STRINGS:
        assert phrase not in content, (
            f"External attribution found in {rel_path}: {phrase!r}"
        )


# ── Doc required terms ────────────────────────────────────────────────────────

@pytest.mark.parametrize("term", DOC_REQUIRED_TERMS)
def test_doc_contains_required_term(term):
    doc = ROOT / V242_DOC
    assert doc.exists()
    assert term in doc.read_text(), (
        f"v2.4.2 doc missing required term: {term!r}"
    )


def test_doc_claims_omnigraph_pending_not_complete():
    doc = ROOT / V242_DOC
    content = doc.read_text()
    assert "Pending" in content, (
        "Doc must say five topics publishing live is Pending (not done yet)"
    )


def test_doc_claims_strict_gate_pending():
    doc = ROOT / V242_DOC
    content = doc.read_text()
    assert "Pending" in content
    assert "v2.4.3" in content, (
        "Doc must say --strict gate is confirmed in v2.4.3"
    )


def test_doc_has_claim_boundary_table():
    doc = ROOT / V242_DOC
    content = doc.read_text()
    assert "Claim Boundary" in content or "claim boundary" in content.lower()
    assert "Pending" in content
    assert "v2.4.1" in content


def test_doc_mentions_ros2_context_node():
    doc = ROOT / V242_DOC
    content = doc.read_text()
    assert "ROS2Context" in content, (
        "Doc must mention ROS2Context initialisation node"
    )


def test_doc_explains_camera_sensor_prim():
    doc = ROOT / V242_DOC
    content = doc.read_text()
    assert "camera_link/sensor" in content, (
        "Doc must specify the Camera sensor prim path for ROS2PublishImage"
    )


def test_doc_says_not_photo_realistic():
    doc = ROOT / V242_DOC
    content = doc.read_text().lower()
    assert "not photo-realistic" in content


@pytest.mark.parametrize("topic", CANONICAL_TOPICS)
def test_doc_mentions_canonical_topic(topic):
    doc = ROOT / V242_DOC
    assert topic in (ROOT / V242_DOC).read_text(), (
        f"v2.4.2 doc must mention canonical topic: {topic}"
    )


@pytest.mark.parametrize("topic", NOVA_CARTER_TOPICS)
def test_doc_does_not_mention_nova_carter_topics(topic):
    doc = ROOT / V242_DOC
    if not doc.exists():
        pytest.skip("Doc not found")
    assert topic not in doc.read_text(), (
        f"Nova Carter topic must not appear in v2.4.2 doc: {topic}"
    )


# ── OmniGraph script content ──────────────────────────────────────────────────

@pytest.mark.parametrize("node_type", OMNIGRAPH_NODE_TYPES)
def test_omnigraph_script_contains_node_type(node_type):
    script = ROOT / V242_OMNIGRAPH_SCRIPT
    assert node_type in script.read_text(), (
        f"OmniGraph script must reference node type: {node_type!r}"
    )


@pytest.mark.parametrize("prim_path", PRIM_PATHS)
def test_omnigraph_script_references_prim_path(prim_path):
    script = ROOT / V242_OMNIGRAPH_SCRIPT
    assert prim_path in script.read_text(), (
        f"OmniGraph script must reference prim path: {prim_path!r}"
    )


@pytest.mark.parametrize("topic", CANONICAL_TOPICS)
def test_omnigraph_script_sets_topic_name(topic):
    script = ROOT / V242_OMNIGRAPH_SCRIPT
    assert topic in script.read_text(), (
        f"OmniGraph script must set topic name: {topic!r}"
    )


def test_omnigraph_script_uses_og_controller_edit():
    script = ROOT / V242_OMNIGRAPH_SCRIPT
    content = script.read_text()
    assert "og.Controller.edit" in content, (
        "Script must use og.Controller.edit API (standard Isaac Sim OmniGraph API)"
    )


def test_omnigraph_script_has_connect_section():
    script = ROOT / V242_OMNIGRAPH_SCRIPT
    content = script.read_text()
    assert "CONNECT" in content, (
        "Script must include CONNECT keys to wire OnPlaybackTick → publishers"
    )


def test_omnigraph_script_connects_playback_tick():
    script = ROOT / V242_OMNIGRAPH_SCRIPT
    content = script.read_text()
    assert "OnPlaybackTick" in content
    assert "outputs:tick" in content, (
        "Script must wire OnPlaybackTick.outputs:tick to downstream nodes"
    )


def test_omnigraph_script_has_no_isaac_sim_hard_dependency():
    """Script must exit 0 when omni.graph.core is not available (CI safety)."""
    result = subprocess.run(
        [sys.executable, str(ROOT / V242_OMNIGRAPH_SCRIPT)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0, (
        f"OmniGraph script must exit 0 without Isaac Sim:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    out = result.stdout
    assert "[OK]" in out or "[INFO]" in out, (
        "Script must print [OK] or [INFO] when run without Isaac Sim"
    )


def test_omnigraph_script_prints_graph_plan():
    result = subprocess.run(
        [sys.executable, str(ROOT / V242_OMNIGRAPH_SCRIPT)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    out = result.stdout
    assert "/World/ROS2ActionGraph" in out, (
        "Script must print the graph path"
    )
    assert "/camera/image_raw" in out
    assert "/odom" in out
    assert "/tf" in out
    assert "/scan" in out
    assert "/cmd_vel" in out


def test_omnigraph_script_prints_prim_paths():
    result = subprocess.run(
        [sys.executable, str(ROOT / V242_OMNIGRAPH_SCRIPT)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    out = result.stdout
    assert "/World/YahboomM3Pro/camera_link/sensor" in out, (
        "Script must print camera prim path in graph plan"
    )
    assert "/World/YahboomM3Pro/base_link" in out
    assert "/World/YahboomM3Pro/lidar_link" in out


@pytest.mark.parametrize("topic", NOVA_CARTER_TOPICS)
def test_omnigraph_script_does_not_reference_nova_carter(topic):
    script = ROOT / V242_OMNIGRAPH_SCRIPT
    assert topic not in script.read_text(), (
        f"OmniGraph script must not reference Nova Carter topic: {topic}"
    )


# ── USDA updated checks ───────────────────────────────────────────────────────

def test_usda_has_camera_sensor_prim():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    content = usda.read_text()
    assert 'def Camera "sensor"' in content, (
        "USDA must contain a Camera sensor prim under camera_link "
        "(required by ROS2PublishImage)"
    )


def test_usda_has_ros2_action_graph_prim():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    content = usda.read_text()
    assert "ROS2ActionGraph" in content, (
        "USDA must contain the ROS2ActionGraph prim stub"
    )


def test_usda_has_omnigraph_scaffold_comments():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    content = usda.read_text()
    assert "ROS2PublishImage" in content
    assert "ROS2SubscribeTwist" in content
    assert "/camera/image_raw" in content
    assert "/cmd_vel" in content
    assert "Pending" in content


def test_usda_camera_sensor_has_focal_length():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    content = usda.read_text()
    assert "focalLength" in content, (
        "Camera sensor prim must have focalLength defined"
    )


def test_usda_camera_sensor_has_clipping_range():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    content = usda.read_text()
    assert "clippingRange" in content


@pytest.mark.parametrize("topic", NOVA_CARTER_TOPICS)
def test_usda_does_not_reference_nova_carter(topic):
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    assert topic not in usda.read_text(), (
        f"USDA must not reference Nova Carter topic: {topic}"
    )


def test_usda_has_no_absolute_paths():
    usda = ROOT / USDA_PATH
    if not usda.exists():
        pytest.skip("USDA not yet generated")
    assert "/home/" not in usda.read_text()


# ── Stage generator updated ───────────────────────────────────────────────────

def test_stage_generator_produces_camera_sensor():
    result = subprocess.run(
        [sys.executable, str(ROOT / V241_STAGE_SCRIPT), "--dry-run"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0
    out = result.stdout
    assert 'def Camera "sensor"' in out, (
        "Stage generator dry-run output must contain Camera sensor prim"
    )


def test_stage_generator_produces_omnigraph_stub():
    result = subprocess.run(
        [sys.executable, str(ROOT / V241_STAGE_SCRIPT), "--dry-run"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0
    out = result.stdout
    assert "ROS2ActionGraph" in out, (
        "Stage generator must include ROS2ActionGraph prim stub in output"
    )


def test_stage_generator_references_v242_doc():
    script = ROOT / V241_STAGE_SCRIPT
    content = script.read_text()
    assert "v2.4.2" in content, (
        "Stage generator must reference v2.4.2 in doc/comments"
    )


# ── README ────────────────────────────────────────────────────────────────────

def test_readme_mentions_v242():
    readme = ROOT / "README.md"
    assert readme.exists()
    content = readme.read_text()
    assert "v2.4.2" in content, "README must mention v2.4.2"
