"""Tests for v2.4 Yahboom M3 Pro first rosbag2 episode collection and validation."""

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent.parent

V24_DOCS = [
    "docs/v2.4_yahboom_first_rosbag_episode.md",
]

V24_SCRIPTS = [
    "scripts/gnm/collect_yahboom_episode.sh",
    "scripts/gnm/validate_yahboom_episode.py",
]

ATTRIBUTION_STRINGS = [
    "generated by",
    "Generated by",
    "co-authored-by",
    "Co-Authored-By",
    "Claude",
    "Anthropic",
    "GPT",
    "ChatGPT",
    "OpenAI",
    "AI assistant",
    "language model",
]

CANONICAL_TOPICS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
]

NOVA_CARTER_TOPICS = [
    "/front_stereo_camera/left/image_raw",
    "/chassis/odom",
    "/front_3d_lidar/lidar_points",
]

V24_DOC_REQUIRED_TERMS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
    "message_count",
    "non-zero",
    "validate_yahboom_episode.py",
    "collect_yahboom_episode.sh",
    "verify_yahboom_live_topics.py",
    "--strict",
    "rosbag2",
    "Nova Carter",
    "Gate A6",
    "v2.5",
    "Pending",
    "30 second",
    "episode_001",
    "episode_metadata.json",
]


# ── File existence ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", V24_DOCS + V24_SCRIPTS)
def test_v24_file_exists(rel_path):
    assert (ROOT / rel_path).exists(), f"v2.4 file missing: {rel_path}"


@pytest.mark.parametrize("rel_path", V24_SCRIPTS)
def test_v24_script_executable(rel_path):
    path = ROOT / rel_path
    assert path.exists(), f"Script missing: {rel_path}"
    assert os.access(path, os.X_OK), f"Script not executable: {rel_path}"


# ── Attribution audit ─────────────────────────────────────────────────────────

@pytest.mark.parametrize("rel_path", V24_DOCS + V24_SCRIPTS)
def test_no_external_attribution(rel_path):
    path = ROOT / rel_path
    if not path.exists():
        pytest.skip(f"File not found: {rel_path}")
    content = path.read_text()
    for phrase in ATTRIBUTION_STRINGS:
        assert phrase not in content, (
            f"External attribution found in {rel_path}: {phrase!r}"
        )


# ── Required terms in doc ─────────────────────────────────────────────────────

@pytest.mark.parametrize("term", V24_DOC_REQUIRED_TERMS)
def test_v24_doc_contains_required_term(term):
    doc = ROOT / "docs" / "v2.4_yahboom_first_rosbag_episode.md"
    assert doc.exists()
    assert term in doc.read_text(), f"v2.4 doc missing required term: {term!r}"


# ── Dependency chain in doc ───────────────────────────────────────────────────

def test_doc_states_gate_runs_before_recording():
    doc = ROOT / "docs" / "v2.4_yahboom_first_rosbag_episode.md"
    content = doc.read_text()
    assert "--strict" in content
    assert "verify_yahboom_live_topics.py" in content
    assert "refuse" in content.lower() or "refused" in content.lower() or "refuses" in content.lower()


def test_doc_names_gate_a6():
    doc = ROOT / "docs" / "v2.4_yahboom_first_rosbag_episode.md"
    assert "Gate A6" in doc.read_text()


# ── Collection script content ─────────────────────────────────────────────────

@pytest.mark.parametrize("topic", CANONICAL_TOPICS)
def test_collect_script_references_canonical_topic(topic):
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    assert topic in script.read_text(), (
        f"collect_yahboom_episode.sh must reference canonical topic: {topic}"
    )


def test_collect_script_calls_gate_verifier():
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    content = script.read_text()
    assert "verify_yahboom_live_topics.py" in content, (
        "collect_yahboom_episode.sh must call the topic gate verifier"
    )
    assert "--strict" in content, (
        "collect_yahboom_episode.sh must call the gate verifier with --strict"
    )


def test_collect_script_has_dry_run_flag():
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    assert "--dry-run" in script.read_text()


def test_collect_script_has_duration_flag():
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    assert "--duration" in script.read_text()


def test_collect_script_has_episode_name_flag():
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    assert "--episode-name" in script.read_text()


def test_collect_script_uses_max_bag_duration():
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    assert "max-bag-duration" in script.read_text(), (
        "collect_yahboom_episode.sh must use --max-bag-duration for timed recording"
    )


def test_collect_script_writes_metadata_json():
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    content = script.read_text()
    assert "episode_metadata.json" in content
    assert "bag_recorded" in content


# ── Validator script content ──────────────────────────────────────────────────

@pytest.mark.parametrize("topic", CANONICAL_TOPICS)
def test_validator_references_canonical_topic(topic):
    script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
    assert topic in script.read_text(), (
        f"validate_yahboom_episode.py must reference: {topic}"
    )


@pytest.mark.parametrize("topic", NOVA_CARTER_TOPICS)
def test_validator_references_nova_carter_topic(topic):
    script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
    assert topic in script.read_text(), (
        f"validate_yahboom_episode.py must check for Nova Carter topic: {topic}"
    )


def test_validator_checks_message_count_nonzero():
    script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
    content = script.read_text()
    assert "message_count" in content
    assert "> 0" in content


def test_validator_checks_minimum_duration():
    script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
    content = script.read_text()
    assert "MIN_DURATION_SECONDS" in content or "30" in content


def test_validator_writes_report_json():
    script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
    content = script.read_text()
    assert "validation.json" in content
    assert "gnm_fleetsafe_v2_4" in content


def test_validator_reads_metadata_yaml():
    script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
    assert "metadata.yaml" in script.read_text()


# ── Dry-run execution ─────────────────────────────────────────────────────────

def test_collect_script_dry_run_exits_zero():
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    result = subprocess.run(
        ["bash", str(script), "--dry-run"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert result.returncode == 0, (
        f"collect_yahboom_episode.sh --dry-run failed:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    out = result.stdout
    assert "[DRY-RUN]" in out or "dry-run" in out.lower()
    assert "[OK]" in out


def test_collect_script_dry_run_prints_gate_command():
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    result = subprocess.run(
        ["bash", str(script), "--dry-run", "--episode-name", "test_ep"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert "verify_yahboom_live_topics.py" in result.stdout
    assert "--strict" in result.stdout


def test_collect_script_dry_run_prints_record_command():
    script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
    result = subprocess.run(
        ["bash", str(script), "--dry-run"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    assert "ros2 bag record" in result.stdout
    for topic in CANONICAL_TOPICS:
        assert topic in result.stdout


def test_collect_script_dry_run_writes_metadata():
    with tempfile.TemporaryDirectory() as tmpdir:
        script = ROOT / "scripts" / "gnm" / "collect_yahboom_episode.sh"
        ep_name = "ci_dry_run_test"
        result = subprocess.run(
            ["bash", str(script), "--dry-run", "--episode-name", ep_name],
            capture_output=True,
            text=True,
            cwd=str(ROOT),
        )
        assert result.returncode == 0
        metadata_path = (
            ROOT / "datasets" / "gnm_fleetsafe_rosbags" / ep_name / "episode_metadata.json"
        )
        assert metadata_path.exists(), "dry-run must write episode_metadata.json"
        data = json.loads(metadata_path.read_text())
        assert data["robot"] == "Yahboom ROSMASTER M3 Pro"
        assert data["dry_run"] is True
        assert data["bag_recorded"] is False
        assert "canonical_topics" in data


def test_validator_exits_zero_without_episode_path():
    script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"validate_yahboom_episode.py must exit 0 without --episode-path:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert "[OK]" in result.stdout


def test_validator_exits_zero_with_nonexistent_path():
    script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
    result = subprocess.run(
        [sys.executable, str(script), "--episode-path", "/tmp/no_such_episode_xyz"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        "validate_yahboom_episode.py must exit 0 when episode path does not exist"
    )
    assert "[OK]" in result.stdout


def test_validator_fails_on_invalid_bag():
    """Supply a metadata.yaml with a missing topic — validator must exit non-zero."""
    with tempfile.TemporaryDirectory() as tmpdir:
        script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
        ep_dir = Path(tmpdir) / "bad_episode"
        bag_dir = ep_dir / "rosbag"
        bag_dir.mkdir(parents=True)

        metadata = {
            "rosbag2_bagfile_information": {
                "duration": {"nanoseconds": 60_000_000_000},
                "message_count": 100,
                "topics_with_message_count": [
                    {
                        "topic_metadata": {"name": "/odom", "type": "nav_msgs/Odometry"},
                        "message_count": 50,
                    }
                ],
            }
        }

        try:
            import yaml
            (bag_dir / "metadata.yaml").write_text(yaml.dump(metadata))
        except ImportError:
            pytest.skip("PyYAML not installed; skipping live metadata parse test")

        result = subprocess.run(
            [sys.executable, str(script), "--episode-path", str(ep_dir)],
            capture_output=True,
            text=True,
        )
        assert result.returncode != 0, (
            "validate_yahboom_episode.py must exit non-zero when canonical topics are missing"
        )
        assert "[FAIL]" in result.stdout


def test_validator_passes_on_valid_bag():
    """Supply a complete metadata.yaml — validator must exit 0 and write report."""
    with tempfile.TemporaryDirectory() as tmpdir:
        script = ROOT / "scripts" / "gnm" / "validate_yahboom_episode.py"
        ep_dir = Path(tmpdir) / "good_episode"
        bag_dir = ep_dir / "rosbag"
        bag_dir.mkdir(parents=True)

        topics_entries = [
            {"topic_metadata": {"name": "/camera/image_raw", "type": "sensor_msgs/Image"}, "message_count": 1800},
            {"topic_metadata": {"name": "/odom", "type": "nav_msgs/Odometry"}, "message_count": 3000},
            {"topic_metadata": {"name": "/tf", "type": "tf2_msgs/TFMessage"}, "message_count": 6000},
            {"topic_metadata": {"name": "/scan", "type": "sensor_msgs/LaserScan"}, "message_count": 600},
            {"topic_metadata": {"name": "/cmd_vel", "type": "geometry_msgs/Twist"}, "message_count": 600},
        ]

        metadata = {
            "rosbag2_bagfile_information": {
                "duration": {"nanoseconds": 60_000_000_000},
                "message_count": sum(e["message_count"] for e in topics_entries),
                "topics_with_message_count": topics_entries,
            }
        }

        try:
            import yaml
            (bag_dir / "metadata.yaml").write_text(yaml.dump(metadata))
        except ImportError:
            pytest.skip("PyYAML not installed; skipping live metadata parse test")

        result = subprocess.run(
            [sys.executable, str(script), "--episode-path", str(ep_dir)],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, (
            f"validate_yahboom_episode.py must exit 0 on a valid bag:\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
        assert "[OK]" in result.stdout
        assert "valid" in result.stdout.lower()

        # Report JSON must be written.
        report_path = ROOT / "results" / "gnm_fleetsafe_v2_4" / "good_episode_validation.json"
        assert report_path.exists(), "Validator must write validation report JSON"
        data = json.loads(report_path.read_text())
        assert data["valid"] is True
        assert data["milestone"] == "v2.4"


# ── README ────────────────────────────────────────────────────────────────────

def test_readme_mentions_v24():
    readme = ROOT / "README.md"
    assert readme.exists()
    assert "v2.4" in readme.read_text(), "README must mention v2.4"


# ── v2.3 gate files still present ─────────────────────────────────────────────

def test_v23_gate_verifier_still_present():
    assert (ROOT / "scripts" / "gnm" / "verify_yahboom_live_topics.py").exists()


def test_v23_import_plan_still_present():
    assert (ROOT / "scripts" / "gnm" / "yahboom_isaac_import_plan.py").exists()
