"""Tests for FleetSafe-GNM v2.0 implementation files."""

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent.parent

V2_FILES = [
    "docs/FLEETSAFE_GNM_IMPLEMENTATION_MANUAL.md",
    "configs/gnm_fleetsafe_isaac.yaml",
    "scripts/gnm/check_ros2_topics.sh",
    "scripts/gnm/collect_isaac_rosbag_episode.sh",
    "scripts/gnm/convert_rosbag_to_gnm_dataset.py",
    "scripts/gnm/train_gnm_from_collected_data.sh",
    "scripts/gnm/eval_gnm_vs_fleetsafe.sh",
    "launch/gnm_fleetsafe_isaac.launch.py",
]

EXECUTABLE_SCRIPTS = [
    "scripts/gnm/check_ros2_topics.sh",
    "scripts/gnm/collect_isaac_rosbag_episode.sh",
    "scripts/gnm/train_gnm_from_collected_data.sh",
    "scripts/gnm/eval_gnm_vs_fleetsafe.sh",
]

ATTRIBUTION_STRINGS = [
    "generated by",
    "Generated by",
    "co-authored-by",
    "Co-Authored-By",
    "Claude",
    "Anthropic",
    "GPT",
    "ChatGPT",
    "OpenAI",
    "AI assistant",
    "language model",
]

MANUAL_REQUIRED_TERMS = [
    "TF",
    "LoRA",
    "Isaac Sim",
    "GNM",
    "FleetSafe",
    "rosbag2",
    "/cmd_vel",
]

CONFIG_REQUIRED_TOPICS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/gnm/cmd_vel_raw",
    "/fleetsafe/cmd_vel_safe",
    "/cmd_vel",
]


@pytest.mark.parametrize("rel_path", V2_FILES)
def test_v2_file_exists(rel_path):
    path = ROOT / rel_path
    assert path.exists(), f"v2.0 file missing: {rel_path}"


@pytest.mark.parametrize("rel_path", EXECUTABLE_SCRIPTS)
def test_script_is_executable(rel_path):
    path = ROOT / rel_path
    assert path.exists(), f"Script missing: {rel_path}"
    assert os.access(path, os.X_OK), f"Script not executable: {rel_path}"


@pytest.mark.parametrize("term", MANUAL_REQUIRED_TERMS)
def test_manual_contains_required_term(term):
    manual = ROOT / "docs" / "FLEETSAFE_GNM_IMPLEMENTATION_MANUAL.md"
    assert manual.exists(), "Implementation manual missing"
    content = manual.read_text()
    assert term in content, f"Manual does not mention: {term}"


@pytest.mark.parametrize("topic", CONFIG_REQUIRED_TOPICS)
def test_config_contains_required_topic(topic):
    config = ROOT / "configs" / "gnm_fleetsafe_isaac.yaml"
    assert config.exists(), "Config file missing"
    content = config.read_text()
    assert topic in content, f"Config does not mention topic: {topic}"


@pytest.mark.parametrize("rel_path", V2_FILES)
def test_no_external_attribution_in_v2_files(rel_path):
    path = ROOT / rel_path
    if not path.exists():
        pytest.skip(f"File not found: {rel_path}")
    content = path.read_text()
    for phrase in ATTRIBUTION_STRINGS:
        assert phrase not in content, (
            f"External attribution string found in {rel_path}: '{phrase}'"
        )


def test_converter_dry_run_creates_manifest(tmp_path):
    output_root = tmp_path / "gnm_fleetsafe_converted"
    rosbag_root = tmp_path / "gnm_fleetsafe_rosbags"
    rosbag_root.mkdir(parents=True)
    episode_name = "test_episode"

    script = ROOT / "scripts" / "gnm" / "convert_rosbag_to_gnm_dataset.py"
    assert script.exists(), "Converter script missing"

    result = subprocess.run(
        [
            sys.executable,
            str(script),
            "--rosbag-root", str(rosbag_root),
            "--output-root", str(output_root),
            "--episode-name", episode_name,
            "--dry-run",
        ],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"Converter dry-run failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    )

    manifest_path = output_root / episode_name / "conversion_manifest.json"
    assert manifest_path.exists(), "Conversion manifest was not created"

    manifest = json.loads(manifest_path.read_text())
    assert manifest["dry_run"] is True
    assert manifest["episode_name"] == episode_name


def test_eval_dry_run_creates_csv_and_markdown(tmp_path, monkeypatch):
    results_dir = tmp_path / "gnm_fleetsafe_v2"

    script = ROOT / "scripts" / "gnm" / "eval_gnm_vs_fleetsafe.sh"
    assert script.exists(), "Eval script missing"

    env = os.environ.copy()
    env["HOME"] = str(tmp_path)

    import tempfile, shutil

    with tempfile.TemporaryDirectory() as repo_root:
        fake_git = Path(repo_root) / ".git"
        fake_git.mkdir()
        results_target = Path(repo_root) / "results" / "gnm_fleetsafe_v2"
        results_target.mkdir(parents=True)

        result = subprocess.run(
            ["bash", str(script), "--dry-run"],
            capture_output=True,
            text=True,
            cwd=repo_root,
            env=env,
        )
        assert result.returncode == 0, (
            f"Eval dry-run failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )

        csv_path = Path(repo_root) / "results" / "gnm_fleetsafe_v2" / "eval_results.csv"
        md_path = Path(repo_root) / "results" / "gnm_fleetsafe_v2" / "eval_summary.md"
        assert csv_path.exists(), "eval_results.csv not created"
        assert md_path.exists(), "eval_summary.md not created"

        csv_content = csv_path.read_text()
        assert "success_rate" in csv_content
        assert "gnm_only" in csv_content
        assert "gnm_plus_fleetsafe" in csv_content

        md_content = md_path.read_text()
        assert "FleetSafe" in md_content
        assert "GNM" in md_content


def test_readme_mentions_v2():
    readme = ROOT / "README.md"
    assert readme.exists(), "README.md missing"
    content = readme.read_text()
    assert "v2.0" in content, "README does not mention v2.0"
    assert "FleetSafe-GNM" in content, "README does not mention FleetSafe-GNM in v2.0 context"


def test_launch_file_importable():
    launch_file = ROOT / "launch" / "gnm_fleetsafe_isaac.launch.py"
    assert launch_file.exists(), "Launch file missing"
    result = subprocess.run(
        [sys.executable, "-c",
         f"import importlib.util; "
         f"spec = importlib.util.spec_from_file_location('launch_file', '{launch_file}'); "
         f"mod = importlib.util.module_from_spec(spec); "
         f"spec.loader.exec_module(mod)"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"Launch file failed to import:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    )


def test_check_ros2_topics_exits_zero_without_ros2():
    script = ROOT / "scripts" / "gnm" / "check_ros2_topics.sh"
    assert script.exists(), "Topic checker script missing"
    result = subprocess.run(
        ["bash", str(script)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"check_ros2_topics.sh must exit 0 when Isaac Sim is not running:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    out = result.stdout.lower()
    assert any(phrase in out for phrase in [
        "skipped", "not found", "dry-run", "[ok]", "non-strict", "isaac sim"
    ]), f"Unexpected output from check_ros2_topics.sh: {result.stdout}"
