"""Tests for v2.1 Isaac ROS 2 bridge verification layer."""

import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent.parent

V21_FILES = [
    "docs/v2.1_isaac_ros2_bridge_checklist.md",
    "docs/yahboom_control_scene_checklist.md",
    "scripts/gnm/check_isaac_bridge.sh",
    "scripts/gnm/verify_live_topics.py",
]

EXECUTABLE_SCRIPTS = [
    "scripts/gnm/check_isaac_bridge.sh",
    "scripts/gnm/verify_live_topics.py",
]

ATTRIBUTION_STRINGS = [
    "generated by",
    "Generated by",
    "co-authored-by",
    "Co-Authored-By",
    "Claude",
    "Anthropic",
    "GPT",
    "ChatGPT",
    "OpenAI",
    "AI assistant",
    "language model",
]

REQUIRED_TOPICS = [
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
]

CHECKLIST_REQUIRED_TERMS = [
    "Isaac Sim",
    "ROS 2",
    "/camera/image_raw",
    "/odom",
    "/tf",
    "/scan",
    "/cmd_vel",
    "--strict",
]

YAHBOOM_CHECKLIST_REQUIRED_TERMS = [
    "Yahboom",
    "yahboom_m3pro",
    "/cmd_vel",
    "Pending",
]


@pytest.mark.parametrize("rel_path", V21_FILES)
def test_v21_file_exists(rel_path):
    path = ROOT / rel_path
    assert path.exists(), f"v2.1 file missing: {rel_path}"


@pytest.mark.parametrize("rel_path", EXECUTABLE_SCRIPTS)
def test_script_is_executable(rel_path):
    path = ROOT / rel_path
    assert path.exists(), f"Script missing: {rel_path}"
    assert os.access(path, os.X_OK), f"Script not executable: {rel_path}"


@pytest.mark.parametrize("term", CHECKLIST_REQUIRED_TERMS)
def test_bridge_checklist_contains_required_term(term):
    checklist = ROOT / "docs" / "v2.1_isaac_ros2_bridge_checklist.md"
    assert checklist.exists(), "v2.1 bridge checklist missing"
    content = checklist.read_text()
    assert term in content, f"Bridge checklist does not mention: {term!r}"


@pytest.mark.parametrize("term", YAHBOOM_CHECKLIST_REQUIRED_TERMS)
def test_yahboom_checklist_contains_required_term(term):
    checklist = ROOT / "docs" / "yahboom_control_scene_checklist.md"
    assert checklist.exists(), "Yahboom checklist missing"
    content = checklist.read_text()
    assert term in content, f"Yahboom checklist does not mention: {term!r}"


@pytest.mark.parametrize("topic", REQUIRED_TOPICS)
def test_bridge_checklist_mentions_required_topic(topic):
    checklist = ROOT / "docs" / "v2.1_isaac_ros2_bridge_checklist.md"
    assert checklist.exists()
    assert topic in checklist.read_text(), (
        f"Bridge checklist does not mention required topic: {topic}"
    )


@pytest.mark.parametrize("topic", REQUIRED_TOPICS)
def test_verify_live_topics_script_mentions_topic(topic):
    script = ROOT / "scripts" / "gnm" / "verify_live_topics.py"
    assert script.exists()
    assert topic in script.read_text(), (
        f"verify_live_topics.py does not reference topic: {topic}"
    )


@pytest.mark.parametrize("rel_path", V21_FILES)
def test_no_external_attribution_in_v21_files(rel_path):
    path = ROOT / rel_path
    if not path.exists():
        pytest.skip(f"File not found: {rel_path}")
    content = path.read_text()
    for phrase in ATTRIBUTION_STRINGS:
        assert phrase not in content, (
            f"External attribution found in {rel_path}: {phrase!r}"
        )


def test_check_isaac_bridge_exits_zero_without_ros2():
    script = ROOT / "scripts" / "gnm" / "check_isaac_bridge.sh"
    assert script.exists(), "check_isaac_bridge.sh missing"
    result = subprocess.run(
        ["bash", str(script)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"check_isaac_bridge.sh must exit 0 without Isaac Sim running:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    out = result.stdout.lower()
    assert any(phrase in out for phrase in [
        "skipped", "not found", "dry-run", "[ok]", "non-strict", "isaac",
    ]), f"Unexpected output: {result.stdout}"


def test_verify_live_topics_exits_zero_without_ros2():
    script = ROOT / "scripts" / "gnm" / "verify_live_topics.py"
    assert script.exists(), "verify_live_topics.py missing"
    result = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"verify_live_topics.py must exit 0 without ROS 2:\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    out = result.stdout
    assert any(phrase in out.lower() for phrase in [
        "[ok]", "skipped", "not found", "non-strict", "[info]", "[missing]",
    ]), f"Unexpected output: {result.stdout}"


def test_verify_live_topics_strict_exits_nonzero_without_ros2():
    script = ROOT / "scripts" / "gnm" / "verify_live_topics.py"
    assert script.exists()
    result = subprocess.run(
        [sys.executable, str(script), "--strict"],
        capture_output=True,
        text=True,
    )
    import shutil
    if shutil.which("ros2") is None:
        assert result.returncode != 0, (
            "verify_live_topics.py --strict must exit non-zero when ROS 2 is absent"
        )
    else:
        pytest.skip("ROS 2 is installed; strict-without-Isaac check not applicable")


def test_check_isaac_bridge_strict_exits_nonzero_without_ros2():
    script = ROOT / "scripts" / "gnm" / "check_isaac_bridge.sh"
    assert script.exists()
    import shutil
    if shutil.which("ros2") is not None:
        pytest.skip("ROS 2 is installed; strict-without-Isaac check not applicable")
    result = subprocess.run(
        ["bash", str(script), "--strict"],
        capture_output=True,
        text=True,
    )
    assert result.returncode != 0, (
        "check_isaac_bridge.sh --strict must exit non-zero when ROS 2 is absent"
    )


def test_readme_mentions_v21():
    readme = ROOT / "README.md"
    assert readme.exists(), "README.md missing"
    content = readme.read_text()
    assert "v2.1" in content, "README does not mention v2.1"
    assert "Isaac ROS 2" in content, "README does not mention Isaac ROS 2 in v2.1 context"


def test_v21_checklist_mentions_yahboom():
    checklist = ROOT / "docs" / "v2.1_isaac_ros2_bridge_checklist.md"
    assert checklist.exists()
    content = checklist.read_text()
    assert "Yahboom" in content, "v2.1 checklist does not reference Yahboom placeholder"


def test_v21_checklist_mentions_scope_limits():
    checklist = ROOT / "docs" / "v2.1_isaac_ros2_bridge_checklist.md"
    content = checklist.read_text()
    assert "No live GNM" in content or "no live GNM" in content.lower() or \
           "does not" in content, \
        "v2.1 checklist should document what is NOT in scope"
