#!/usr/bin/env python3
"""Audit the degree to which vlntube_fleetsafe instructions encode target-region information.

The 253 instructions in datasets/vlntube/ were generated by the VLNTube instube/ pipeline
(Gemini API, gemini-2.5-flash) fed the rendered trajectory image sequence.  The generator
prompt explicitly required an endpoint description ("Stop in front of …").  This means:

- The instruction generator SAW the full trajectory, including goal-region frames.
- The endpoint description in each instruction was derived from visual content near the goal.
- goal_pos (geometric, A* planning) was NOT included in the Gemini prompt.
- No explicit "target frame" was identified to Gemini; it saw the whole sequence.

This is classified as INDIRECT_TARGET_VISUAL_EXPOSURE — the standard formulation for
automatically constructed VLN benchmarks.  It does NOT invalidate the evaluation, but
the claim boundary is "generated-language grounding" not "human-language generalisation".

Exposure classifications
------------------------
NO_TARGET_EXPOSURE_CONFIRMED
    Confirmed that no goal-region information was visible to the generator.
    Applies only when frames near goal_pos are demonstrably absent from the input sequence.

INDIRECT_TARGET_VISUAL_EXPOSURE
    Generator saw a sequence that includes or likely includes goal-region frames.
    The endpoint description may encode goal-region visual information.
    Standard for auto-generated VLN datasets.

DIRECT_TARGET_FRAME_EXPOSURE
    A specific target frame was explicitly provided to the generator.
    Not the case here.

GOAL_POSE_EXPOSURE
    goal_pos coordinates were included in the generator prompt.
    Not the case here.

UNKNOWN
    Frame sampling information or generator input cannot be verified.

Usage
-----
    python3 scripts/gnm/audit_instruction_target_exposure.py
    python3 scripts/gnm/audit_instruction_target_exposure.py \\
        --output-dir results/track_b_language/target_exposure
"""
from __future__ import annotations

import argparse
import json
import math
import pickle
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

FLEETSAFE_VLNTUBE = Path("/home/favl/robotics/FleetSafe-VisualNav-Benchmark/datasets/vlntube")

# VLNTube instube/ pipeline constants (from gemini_images_analyzer.py)
INSTUBE_MAX_FRAMES = 30
INSTUBE_GENERATOR_MODEL = "gemini-2.5-flash"
INSTUBE_GENERATOR_PROVIDER = "Google"
INSTUBE_GENERATOR_PROMPT_TEMPLATE = "VLN_PROMPT_IMAGE_SEQUENCE"
INSTUBE_GOAL_POS_IN_PROMPT = False
INSTUBE_TARGET_FRAME_EXPLICIT = False
# Uniform sampling: last frame index is always included
# indices = [int(i * (n-1) / (INSTUBE_MAX_FRAMES-1)) for i in range(INSTUBE_MAX_FRAMES)]
# -> index INSTUBE_MAX_FRAMES-1 maps to n-1 (last frame)
INSTUBE_FINAL_FRAME_ALWAYS_INCLUDED = True

SUCCESS_RADIUS_M = 3.0


def _load_trajectory(ep_dir: Path) -> tuple[np.ndarray | None, dict | None]:
    """Load (positions_xy, episode_info) from episode directory."""
    traj_file = ep_dir / "traj_data.pkl"
    ep_info_file = ep_dir / "episode_info.json"
    positions = None
    ep_info = None
    if traj_file.exists():
        try:
            data = pickle.loads(traj_file.read_bytes())
            raw = np.asarray(data.get("position", []))
            if raw.ndim == 2 and raw.shape[1] >= 2:
                positions = raw[:, :2]
        except Exception:
            pass
    if ep_info_file.exists():
        try:
            ep_info = json.loads(ep_info_file.read_text())
        except Exception:
            pass
    return positions, ep_info


def _frames_within_radius(
    positions: np.ndarray,
    goal_xy: np.ndarray,
    radius_m: float,
) -> list[int]:
    """Return indices of trajectory frames within radius of goal."""
    dists = np.linalg.norm(positions - goal_xy, axis=1)
    return [int(i) for i in np.where(dists <= radius_m)[0]]


def _sampled_frame_indices(n_total: int, max_frames: int = INSTUBE_MAX_FRAMES) -> list[int]:
    """Reproduce the instube uniform sampling indices.

    Mirrors instube/gemini_images_analyzer.py:
        indices = [int(i * (n-1) / (max_frames-1)) for i in range(max_frames)]
    Returns sorted deduplicated list.
    """
    if n_total <= max_frames:
        return list(range(n_total))
    indices = [
        int(i * (n_total - 1) / (max_frames - 1))
        for i in range(max_frames)
    ]
    return sorted(set(indices))


def _classify_episode(
    ep_dir: Path,
    positions: np.ndarray,
    goal_pos: list[float],
) -> dict:
    """Classify target exposure for one episode."""
    n_total = len(positions)
    goal_xy = np.array(goal_pos[:2])

    # Frames the generator saw
    sampled_indices = _sampled_frame_indices(n_total)
    final_frame_included = INSTUBE_FINAL_FRAME_ALWAYS_INCLUDED and (n_total - 1) in sampled_indices

    # Goal-region frames in trajectory
    goal_region_indices = _frames_within_radius(positions, goal_xy, SUCCESS_RADIUS_M)
    sampled_goal_region = [i for i in sampled_indices if i in set(goal_region_indices)]

    # Distance of last sampled frame from goal
    last_sampled_idx = sampled_indices[-1]
    last_sampled_dist = float(np.linalg.norm(positions[last_sampled_idx] - goal_xy))

    # Exposure classification
    if INSTUBE_GOAL_POS_IN_PROMPT:
        exposure = "GOAL_POSE_EXPOSURE"
    elif INSTUBE_TARGET_FRAME_EXPLICIT:
        exposure = "DIRECT_TARGET_FRAME_EXPOSURE"
    elif sampled_goal_region:
        # Confirmed: generator saw goal-region frames
        exposure = "INDIRECT_TARGET_VISUAL_EXPOSURE"
    elif final_frame_included:
        # Final frame included; not confirmed in radius, but generator saw trajectory end
        exposure = "INDIRECT_TARGET_VISUAL_EXPOSURE"
    else:
        exposure = "UNKNOWN"

    n_frames = len(list(ep_dir.glob("*.jpg")))

    return {
        "episode_id":                    ep_dir.name,
        "n_trajectory_steps":            n_total,
        "n_jpg_frames":                  n_frames,
        "n_sampled_frames":              len(sampled_indices),
        "final_frame_included":          final_frame_included,
        "goal_region_frames_in_traj":    len(goal_region_indices),
        "goal_region_frames_sampled":    len(sampled_goal_region),
        "last_sampled_frame_dist_m":     round(last_sampled_dist, 3),
        "instruction_generated_from_full_trajectory": True,
        "instruction_generated_from_sampled_frames":  n_total > INSTUBE_MAX_FRAMES,
        "goal_pos_in_generator_prompt":  INSTUBE_GOAL_POS_IN_PROMPT,
        "target_frame_explicit":         INSTUBE_TARGET_FRAME_EXPLICIT,
        "final_frame_visible_to_generator": final_frame_included,
        "goal_region_visible_to_generator": len(sampled_goal_region) > 0 or final_frame_included,
        "target_exposure_classification": exposure,
        "instruction_target_independent": not INSTUBE_GOAL_POS_IN_PROMPT and not INSTUBE_TARGET_FRAME_EXPLICIT,
        "target_retrieval_independent":   True,  # goal_pos from scene-graph geometry
        "instruction_created_before_model_run": True,
        "evaluation_eligible":            True,
        "leakage_risk":                  "low_standard_vln",
        "exclusion_reason":              None,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--output-dir",
        default="results/track_b_language/target_exposure",
        help="Output directory (default: results/track_b_language/target_exposure)",
    )
    parser.add_argument(
        "--vlntube-root",
        default=str(FLEETSAFE_VLNTUBE),
        help=f"vlntube dataset root (default: {FLEETSAFE_VLNTUBE})",
    )
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    vlntube = Path(args.vlntube_root)

    if not vlntube.is_dir():
        print(f"ERROR: vlntube root not found: {vlntube}", file=sys.stderr)
        sys.exit(1)

    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    episodes = []

    for split in ("train", "val"):
        split_dir = vlntube / split
        if not split_dir.is_dir():
            continue
        for ep_dir in sorted(split_dir.iterdir()):
            if not ep_dir.is_dir():
                continue
            positions, ep_info = _load_trajectory(ep_dir)
            if positions is None or ep_info is None:
                continue
            goal = ep_info.get("goal_pos")
            if goal is None:
                continue
            ep_record = _classify_episode(ep_dir, positions, goal)
            ep_record["split"] = split
            ep_record["scene_id"] = ep_info.get("scan", "")
            episodes.append(ep_record)

    # Aggregate
    n_total = len(episodes)
    by_class: dict[str, int] = {}
    n_goal_region_visible = 0
    n_final_frame_included = 0
    n_sampled_only = 0
    n_eligible = 0

    for ep in episodes:
        c = ep["target_exposure_classification"]
        by_class[c] = by_class.get(c, 0) + 1
        if ep["goal_region_visible_to_generator"]:
            n_goal_region_visible += 1
        if ep["final_frame_included"]:
            n_final_frame_included += 1
        if ep["instruction_generated_from_sampled_frames"]:
            n_sampled_only += 1
        if ep["evaluation_eligible"]:
            n_eligible += 1

    aggregate = {
        "audit_timestamp":                 timestamp,
        "vlntube_root":                    str(vlntube),
        "total_episodes":                  n_total,
        "generator_model":                 INSTUBE_GENERATOR_MODEL,
        "generator_provider":              INSTUBE_GENERATOR_PROVIDER,
        "generator_prompt_template":       INSTUBE_GENERATOR_PROMPT_TEMPLATE,
        "generator_script":                "external/VLNTube/instube/gemini_images_analyzer.py",
        "max_frames_to_generator":         INSTUBE_MAX_FRAMES,
        "goal_pos_in_generator_prompt":    INSTUBE_GOAL_POS_IN_PROMPT,
        "target_frame_explicit":           INSTUBE_TARGET_FRAME_EXPLICIT,
        "final_frame_always_included":     INSTUBE_FINAL_FRAME_ALWAYS_INCLUDED,
        "exposure_classification_counts":  by_class,
        "episodes_final_frame_included":   n_final_frame_included,
        "episodes_goal_region_visible":    n_goal_region_visible,
        "episodes_sampled_not_full_traj":  n_sampled_only,
        "evaluation_eligible":             n_eligible,
        "claim_boundary": (
            "These are upstream Gemini-generated instructions (not human-authored). "
            "The instruction generator saw trajectory frames including goal-region frames "
            "(INDIRECT_TARGET_VISUAL_EXPOSURE). This is standard for auto-generated VLN "
            "benchmarks. Evaluation results should be labelled 'generated-language grounding', "
            "not 'human-language generalisation'."
        ),
    }

    # Write outputs
    with open(out_dir / "episode_exposure.jsonl", "w") as f:
        for ep in episodes:
            f.write(json.dumps(ep) + "\n")

    (out_dir / "aggregate.json").write_text(json.dumps(aggregate, indent=2))

    # Markdown report
    lines = [
        "# Instruction Target-Exposure Audit",
        "",
        f"**Date:** {timestamp[:10]}",
        f"**Episodes audited:** {n_total}",
        "",
        "## Generator provenance",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Model | {INSTUBE_GENERATOR_MODEL} |",
        f"| Provider | {INSTUBE_GENERATOR_PROVIDER} |",
        f"| Script | `external/VLNTube/instube/gemini_images_analyzer.py` |",
        f"| Prompt template | {INSTUBE_GENERATOR_PROMPT_TEMPLATE} |",
        f"| Max frames per call | {INSTUBE_MAX_FRAMES} |",
        f"| goal_pos in prompt | {INSTUBE_GOAL_POS_IN_PROMPT} |",
        f"| Target frame explicit | {INSTUBE_TARGET_FRAME_EXPLICIT} |",
        f"| Final frame always sampled | {INSTUBE_FINAL_FRAME_ALWAYS_INCLUDED} |",
        "",
        "## Exposure classification",
        "",
        "| Classification | Count |",
        "|----------------|-------|",
    ]
    for cls, cnt in sorted(by_class.items()):
        lines.append(f"| `{cls}` | {cnt} |")

    lines += [
        "",
        "## Summary statistics",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Goal-region frames visible to generator | {n_goal_region_visible} |",
        f"| Final trajectory frame included | {n_final_frame_included} |",
        f"| Episodes where trajectory was uniformly sampled | {n_sampled_only} |",
        f"| Evaluation eligible | {n_eligible} |",
        "",
        "## Claim boundary",
        "",
        "> " + aggregate["claim_boundary"],
        "",
        "## Classification definitions",
        "",
        "| Code | Meaning |",
        "|------|---------|",
        "| `INDIRECT_TARGET_VISUAL_EXPOSURE` | Generator saw trajectory sequence including goal-region frames; endpoint description derived from those frames. Standard for auto-generated VLN. |",
        "| `DIRECT_TARGET_FRAME_EXPOSURE` | A specific target frame was explicitly given to the generator. Not the case here. |",
        "| `GOAL_POSE_EXPOSURE` | goal_pos coordinates were in the generator prompt. Not the case here. |",
        "| `NO_TARGET_EXPOSURE_CONFIRMED` | Confirmed no goal-region frames in generator input. Not the case here. |",
        "| `UNKNOWN` | Cannot verify generator input. |",
    ]
    (out_dir / "report.md").write_text("\n".join(lines))

    print(f"Target exposure audit complete: {n_total} episodes")
    print(f"Classification counts: {by_class}")
    print(f"Output: {out_dir}")


if __name__ == "__main__":
    main()
